services:
  - type: web
    name: nutrition-calculator
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --worker-class sync --keep-alive 65 --graceful-timeout 120 --log-level info --access-logfile - --error-logfile - --bind 0.0.0.0:$PORT
    healthCheckPath: /api/check-auth
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
